language: python
python:
  - '2.7'
  - '3.4'
addons:
  apt:
    packages:
      - glpk-utils
install:
  - pip install -r requirements.txt
  - python setup.py -q install

script:
  - flake8
  - py.test
